#!/bin/bash

CWD=$PWD
until [ $CWD == / ]; do
    MVNW=$CWD/mvnw
    if [ -e $MVNW ]; then
        exec $MVNW $@
    fi
    CWD=$(dirname $CWD)
done

echo No Maven wrapper found, using $(which mvn)
exec mvn "$@"
